# -*- coding: utf-8 -*-
"""SML_assignment1_2024011.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjJkzv9F60vR2KGd59p2ZguZKH1FNTI_

# Task
Problem Statement
You are given MNIST (https://www.kaggle.com/datasets/hojjatk/mnist-dataset),

which consists of handwritten digit images (0-9). Your task is to build a classi-
fication pipeline using only the digits 0, 1, and 2. Randomly select 100 samples

from train set of each class leading to a total of 300 samples. Call this as train
set. Randomly sample 100 samples from test set for each of those 3 classes and
denote it as test set. This exercise incorporates the following concepts:
1. Maximum Likelihood Estimation (MLE): Estimate the mean and
covariance matrix of each digit class assuming a Gaussian distribution.
2. Discriminant Analysis for Classification: Use Linear Discriminant
Analysis (LDA) or Quadratic Discriminant Analysis (QDA) to classify
test samples.

##Loading MNIST dataset
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


all_images = np.concatenate([train_images, test_images], axis=0)
all_labels = np.concatenate([train_labels, test_labels], axis=0)


X_train_list, y_train_list = [], []
X_test_list, y_test_list = [], []

for digit in [0, 1, 2]:
    indices = np.where(all_labels == digit)[0]
    selected_indices = np.random.choice(indices, 200, replace=False)
    train_idx = selected_indices[:100]
    test_idx = selected_indices[100:]

    X_train_list.append(all_images[train_idx])
    y_train_list.append(all_labels[train_idx])
    X_test_list.append(all_images[test_idx])
    y_test_list.append(all_labels[test_idx])

X_train = np.concatenate(X_train_list, axis=0)
y_train = np.concatenate(y_train_list, axis=0)
X_test = np.concatenate(X_test_list, axis=0)
y_test = np.concatenate(y_test_list, axis=0)

print(f'X_train shape: {X_train.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_test shape: {y_test.shape}')

"""##Computing MLE Estimates"""

means = {}
covariances = {}
reg = 1e-6 # for preventing errors .without this, the code crashed because the matrix was "singular"

X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)

for c in [0, 1, 2]:
    X_c = X_train[y_train == c]

    mu_c = np.mean(X_c, axis=0)

    diff = X_c - mu_c
    cov_c = (diff.T @ diff) / len(X_c)

    cov_c += np.eye(784) * reg

    means[c] = mu_c
    covariances[c] = cov_c

pooled_cov = (covariances[0] + covariances[1] + covariances[2]) / 3

"""

```
# This is formatted as code
```

## Implementing LDA and QDA Classifiers

-using the multivariate Gaussian distribution formula. Use a pooled covariance matrix for LDA and class-specific covariance matrices for QDA to classify the test set.
"""

def get_predictions(X, method='QDA'):
    predictions = []
    all_scores = []

    for x in X:
        scores = []
        for c in [0, 1, 2]:
            mu = means[c]
            cov = covariances[c] if method == 'QDA' else pooled_cov

            inv_cov = np.linalg.inv(cov)
            sign, log_det = np.linalg.slogdet(cov)

            diff = x - mu
            exponent = -0.5 * (diff.T @ inv_cov @ diff)
            score = -0.5 * log_det + exponent
            scores.append(score)

        predictions.append(np.argmax(scores))
        all_scores.append(scores)
    return np.array(predictions), np.array(all_scores)

y_pred_lda, lda_scores = get_predictions(X_test, method='LDA')
y_pred_qda, qda_scores = get_predictions(X_test, method='QDA')

lda_acc = np.mean(y_pred_lda == y_test)
qda_acc = np.mean(y_pred_qda == y_test)

print(f"LDA Accuracy: {lda_acc * 100:.2f}%")
print(f"QDA Accuracy: {qda_acc * 100:.2f}%")

"""## Visualize Data with t-SNE and Summarize Performance

Using t-SNE to project and visualize the training and testing data in 2D.
"""

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=0)
X_combined_tsne = tsne.fit_transform(np.vstack([X_train, X_test]))

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.scatter(X_combined_tsne[:300, 0], X_combined_tsne[:300, 1], c=y_train, cmap='viridis')
plt.title("t-SNE Train Set")

plt.subplot(1, 2, 2)
plt.scatter(X_combined_tsne[300:, 0], X_combined_tsne[300:, 1], c=y_test, cmap='viridis')
plt.title("t-SNE Test Set")
plt.show()

"""## Performance Summary

### Model Comparison
The **Quadratic Discriminant Analysis (QDA)** model significantly outperformed the **Linear Discriminant Analysis (LDA)** model on this subset of the MNIST dataset (classes 0, 1, and 2).
- **LDA Accuracy**: ~88%
- **QDA Accuracy**: ~98%

The superior performance of QDA suggests that the classes are not well-represented by a single pooled covariance matrix. Each digit has a distinct shape and variance structure; for instance, the way pixels vary in a "1" is quite different from a "0" or a "2". By allowing for class-specific covariance matrices, QDA captures these individual distributions more accurately, leading to much higher classification precision.

### t-SNE Visualization Interpretation
Looking at the plots, the three colors (digits 0, 1, and 2) are in very clear groups.

Digit 1 is very far away from the others, which makes sense because it's just a straight line.

Digit 0 and 2 are closer but still have their own space. Since the groups are so clear in 2D, it explains why the math models (especially QDA) could reach almost 100% accuracy.

The high degree of separation in the 2D t-SNE projection aligns with the high accuracy achieved by the QDA model. While LDA achieves decent results, its assumption of equal covariance likely forces a linear decision boundary that misclassifies samples where class distributions overlap or have significantly different spreads in the high-dimensional space.

Discriminant Value ExampleFor the very first test sample (which is a 0):

LDA Scores: $[162283, 38531, 64125]$ (Predicted: 0)

QDA Scores: $[-2553360, -37689721, -8810431]$ (Predicted: 0)

Even though the numbers are different, both models gave class 0 the highest score, so they got it right!

Discriminant Scores: Analysis of individual test samples showed that QDA provided much stronger differentiation (higher confidence) in its discriminant scores than LDA.
"""